ansible_user: vagrant
kube_nodes:
  - ip: "192.168.121.10"
    hostname: "kubes-master"
  - ip: "192.168.121.21"
    hostname: "kubes-node1"
  - ip: "192.168.121.22"
    hostname: "kubes-node2"
  - ip: "192.168.121.23"
    hostname: "kubes-backup"
  - ip: "192.168.121.24"
    hostname: "kubes-argocd-node"
  - ip: "192.168.121.25"
    hostname: "kubes-ingress-controller"
