- name: Add Nginx Ingress Helm repo
  ansible.builtin.command:
    cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  register: helm_repo_add
  changed_when: helm_repo_add.rc == 0
  tags: helm_repo

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  tags: helm_update

- name: Install Nginx Ingress Controller
  ansible.builtin.command: >
    helm upgrade --install nginx-ingress {{ nginx_ingress_chart }}
    --namespace {{ nginx_ingress_namespace }} --create-namespace
  environment:
    KUBECONFIG: /home/vagrant/.kube/config
  tags: nginx_install
