- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  ansible.builtin.shell:
    cmd: apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Disable swap
  ansible.builtin.shell:
    cmd: swapoff -a
  failed_when: false

- name: Disable swap in /etc/fstab
  ansible.builtin.shell:
    cmd: sed -i '/swap/s/^/#/' /etc/fstab

- name: Reset Kubernetes cluster with kubeadm
  ansible.builtin.command:
    cmd: kubeadm reset -f

- name: Delete UFW rules
  ufw:
    rule: deny
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items: "{{ ufw_deny_rules }}"

- name: Reload sysctl configuration
  ansible.builtin.command:
    cmd: sysctl --system

- name: Initialize Kubernetes cluster
  ansible.builtin.shell:
    cmd: kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=192.168.0.0/16
  register: init_output

- name: Extract kubeadm join command
  ansible.builtin.set_fact:
    join_command: "{{ init_output.stdout | regex_search('kubeadm join .*', multiline=True) | regex_replace('\\s*\\\\\\s*', ' ') }} --discovery-token-ca-cert-hash {{ init_output.stdout | regex_search('sha256:[a-f0-9]{64}', multiline=True) }}"

- name: Extract IP, token, and hash from join command
  ansible.builtin.set_fact:
    join_ip: "{{ (join_command.split(' ') | reject('equalto', '') | list)[2].split(':')[0] }}"
    join_token: "{{ (join_command.split(' ') | reject('equalto', '') | list)[4] }}"
    join_sha256: "{{ (join_command.split(' ') | reject('equalto', '') | list)[6].split(':')[1] }}"
  delegate_to: localhost
  run_once: true

- name: Debug extracted variables
  ansible.builtin.debug:
    msg:
      - "Join IP: {{ join_ip }}"
      - "Join Token: {{ join_token }}"
      - "Join SHA256: {{ join_sha256 }}"
    
- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Add UFW rules
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items: "{{ ufw_allow_rules }}"

- name: Download Calico manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml"
    dest: /tmp/calico.yaml

- name: Ensure CALICO_IPV4POOL_CIDR is uncommented
  ansible.builtin.replace:
    path: /tmp/calico.yaml
    regexp: "#[ ]*- name: CALICO_IPV4POOL_CIDR"
    replace: "- name: CALICO_IPV4POOL_CIDR"

- name: Update CALICO_IPV4POOL_CIDR value
  ansible.builtin.replace:
    path: /tmp/calico.yaml
    regexp: "- name: CALICO_IPV4POOL_CIDR.*"
    replace: "- name: CALICO_IPV4POOL_CIDR\n              value: \"192.168.0.0/16\""

- name: Add IP_AUTODETECTION_METHOD using sed
  ansible.builtin.shell: |
    sed -i '/value: "autodetect"/a\
                - name: IP_AUTODETECTION_METHOD\n              value: "interface=enp0s8"\n            - name: IP_AUTODETECTION_SKIP_METHOD\n              value: "skip-interface=enp0s3"' /tmp/calico.yaml

- name: Apply Calico manifest to Kubernetes
  ansible.builtin.shell: |
    kubectl apply -f /tmp/calico.yaml
  environment:
    KUBECONFIG: /home/vagrant/.kube/config
