- name: Install Kubernetes components
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  ansible.builtin.shell:
    cmd: apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Disable swap
  ansible.builtin.shell:
    cmd: swapoff -a
  failed_when: false

- name: Disable swap in /etc/fstab
  ansible.builtin.shell:
    cmd: sed -i '/swap/s/^/#/' /etc/fstab
    
- name: Ensure directory for fetched kubeconfigs exists
  ansible.builtin.file:
    path: /tmp/kubeconfigs
    state: directory
    mode: '0755'
    
- name: Create pki directory
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Fetch kubeconfig from master
  ansible.builtin.fetch:
    src: /home/vagrant/.kube/config
    dest: /tmp/kubeconfigs/
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"

- name: Copy kubeconfig file to controller nodes
  ansible.builtin.copy:
    src: /tmp/kubeconfigs/config
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Fetch ca.crt from master
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/ca.crt
    dest: /tmp/kubeconfigs/
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"

- name: Copy apiserver.yaml file to controller nodes
  ansible.builtin.copy:
    src: /tmp/kubeconfigs/ca.crt
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0600'
    
- name: Fetch apiserver.yaml from master
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/ca.key
    dest: /tmp/kubeconfigs/
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"

- name: Copy apiserver.yaml file to controller nodes
  ansible.builtin.copy:
    src: /tmp/kubeconfigs/ca.key
    dest: /etc/kubernetes/pki/ca.key
    owner: root
    group: root
    mode: '0600'

- name: Set node IP for kubelet
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: 'KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}'

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
