---
- name: Open ports using iptables
  hosts: all
  become: yes
  vars:
    iptables_rules:
      # Kubernetes 관련
      - { port: 6443, protocol: tcp }    # Kubernetes API
      - { port: 8472, protocol: udp }   # Flannel
      - { port: 4789, protocol: udp }   # Flannel
      
      # Flask 관련
      - { port: 5000, protocol: tcp }  # Flask 기본 포트
      - { port: 8000, protocol: tcp }  # Gunicorn 기본 포트

      # Nginx
      - { port: 80, protocol: tcp }    # HTTP
      - { port: 443, protocol: tcp }   # HTTPS

      # MySQL
      - { port: 3306, protocol: tcp }  # MySQL Database

      # Prometheus 및 모니터링 관련
      - { port: 9090, protocol: tcp }  # Prometheus
      - { port: 9100, protocol: tcp }  # Node Exporter
      - { port: 9093, protocol: tcp }  # Alert Manager
      - { port: 3000, protocol: tcp }  # Grafana

      # GitHub Actions 및 ArgoCD
      - { port: 8080, protocol: tcp }  # ArgoCD Web UI

      # 기타 AWS 및 네트워크 관련
      - { port: 25, protocol: tcp }    # AWS SES (SMTP)
      - { port: 465, protocol: tcp }   # AWS SES (SMTP over SSL)
      - { port: 587, protocol: tcp }   # AWS SES (STARTTLS)
      - { port: 5671, protocol: tcp }  # AWS SNS (AMQP over SSL)
      - { port: 5672, protocol: tcp }  # AWSd SNS (AMQP)

      # VPN 및 VPC
      - { port: 1194, protocol: udp }  # OpenVPN
      - { port: 4500, protocol: udp }  # IPSec NAT Traversal
      - { port: 500, protocol: udp }   # IPSec IKE

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
    
    - name: Ensure iptables-persistent is installed
      apt:
        name: iptables-persistent
        state: present

    - name: Add iptables rules
      lineinfile:
        path: /etc/iptables/rules.v4
        line: "-A INPUT -p {{ item.protocol }} --dport {{ item.port }} -j ACCEPT"
        state: present
      with_items: "{{ iptables_rules }}"

    - name: Apply iptables rules
      shell: |
        iptables -A INPUT -p {{ item.protocol }} --dport {{ item.port }} -j ACCEPT
        iptables-save > /etc/iptables/rules.v4
      with_items: "{{ iptables_rules }}"
      args:
        executable: /bin/bash

    - name: Restart iptables-persistent service
      service:
        name: netfilter-persistent
        state: restarted
