---
- name: Copy ssh key
  hosts: localhost
  roles:
    - cpssh

- name: Open ports 
  hosts: all
  become: yes
  roles:
    - ufw

- name: Configure NTP on servers
  hosts: all
  become: yes
  roles:
    - ntp
