---
- name: Setup
  hosts: localhost
  vars:
    ansible_user: vagrant
    kube_nodes:
      - ip: "192.168.121.10"
        hostname: "final-kube-master"
      - ip: "192.168.121.21"
        hostname: "final-kube-node1"
      - ip: "192.168.121.22"
        hostname: "final-kube-node2"
      - ip: "192.168.121.23"
        hostname: "final-kube-setting-node"
  tasks:
    - name: Set /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present
      loop: "{{ kube_nodes }}"
      become: yes

    - name: Install sshpass
      apt:
        name: sshpass
        state: present
      become: yes

    - name: Generate SSH key if not exists
      command: ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
      args:
        creates: ~/.ssh/id_rsa

    - name: Copy SSH key to nodes
      shell: |
        sshpass -p "{{ ansible_user }}" ssh-copy-id -o StrictHostKeyChecking=no {{ item.hostname }}
      loop: "{{ kube_nodes }}"

    - name: Add nodes to known_hosts
      shell: |
        ssh-keyscan -H {{ item.ip }} >> ~/.ssh/known_hosts
      loop: "{{ kube_nodes }}"
