---
- name: Setup
  hosts: localhost
  vars:
    ansible_user: vagrant
    kube_nodes:
      - ip: "192.168.121.10"
        hostname: "final-kube-master"
      - ip: "192.168.121.21"
        hostname: "final-kube-node1"
      - ip: "192.168.121.22"
        hostname: "final-kube-node2"
      - ip: "192.168.121.23"
        hostname: "final-kube-setting-node"
  tasks:
    - name: Set /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present
      loop: "{{ kube_nodes }}"
      become: yes

    - name: Ensure common's tasks directory exists
      file:
        path: "{{ ansible_env.HOME }}/project/kubeinst/roles/common/tasks"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Ensure master's tasks directory exists
      file:
        path: "{{ ansible_env.HOME }}/project/kubeinst/roles/master/tasks"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Ensure master's handlers directory exists
      file:
        path: "{{ ansible_env.HOME }}/project/kubeinst/roles/master/handlers"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Ensure workers' tasks directory exists
      file:
        path: "{{ ansible_env.HOME }}/project/kubeinst/roles/workers/tasks"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Ensure workers' handlers directory exists
      file:
        path: "{{ ansible_env.HOME }}/project/kubeinst/roles/workers/handlers"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create inventory files
      blockinfile:
        path: "{{ item }}"
        create: yes
        block: |
          [master]
          {{ kube_nodes[0].hostname }} ansible_host={{ kube_nodes[0].ip }}

          [etcd]
          {{ kube_nodes[0].hostname }} ansible_host={{ kube_nodes[0].ip }}

          [workers]
          {{ kube_nodes[1].hostname }} ansible_host={{ kube_nodes[1].ip }}
          {{ kube_nodes[2].hostname }} ansible_host={{ kube_nodes[2].ip }}
          {{ kube_nodes[3].hostname }} ansible_host={{ kube_nodes[3].ip }}

          [all:vars]
          ansible_python_interpreter=/usr/bin/python3
      loop:
        - "{{ ansible_env.HOME }}/project/kubeinst/inventory"
        - "{{ ansible_env.HOME }}/project/setup/inventory"
        
    - name: Create ansible.cfg file
      blockinfile:
        path: "{{ item }}"
        create: yes
        content: |
          [defaults]
          inventory = ./inventory
          remote_user = "{{ ansible_user }}"

          [privilege_escalation]
          become = true
          become_method = sudo
          become_ask_pass = false
      loop:
        - "{{ ansible_env.HOME }}/project/kubeinst/ansible.cfg"
        - "{{ ansible_env.HOME }}/project/setup/ansible.cfg"

    - name: Install sshpass
      apt:
        name: sshpass
        state: present
      become: yes

    - name: Generate SSH key if not exists
      command: ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
      args:
        creates: ~/.ssh/id_rsa

    - name: Copy SSH key to nodes
      shell: |
        sshpass -p "{{ ansible_user }}" ssh-copy-id -o StrictHostKeyChecking=no {{ item.hostname }}
      loop: "{{ kube_nodes }}"

    - name: Add nodes to known_hosts
      shell: |
        ssh-keyscan -H {{ item.ip }} >> ~/.ssh/known_hosts
      loop: "{{ kube_nodes }}"
