---
- name: Copy ssh key
  hosts: all
  roles:
    - cpssh

- name: Open ports using iptables
  hosts: all
  become: yes
  roles:
    - iptables

- name: Configure NTP on servers
  hosts: all
  become: yes
  roles:
    - ntp
