- name: Set up common configurations
  hosts: main
  roles:
    - common

- name: Configure master node
  hosts: master
  roles:
    - master

- name: Configure worker nodes
  hosts: workers
  roles:
    - workers
