- name: Set up common configurations
  hosts: all
  become: yes
  roles:
    - common

- name: Configure master node
  hosts: master
  become: yes
  roles:
    - master

- name: Configure worker nodes
  hosts: workers
  become: yes
  roles:
    - workers
