- name: Flush all iptables rules
  ansible.builtin.command:
    cmd: iptables -F

- name: Flush NAT iptables rules
  ansible.builtin.command:
    cmd: iptables -t nat -F

- name: Flush mangle iptables rules
  ansible.builtin.command:
    cmd: iptables -t mangle -F

- name: Delete all iptables chains
  ansible.builtin.command:
    cmd: iptables -X

- name: Open kubernetes api port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 6443
    jump: ACCEPT

- name: Open flannel port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 8472
    jump: ACCEPT

- name: Open flannel sub-port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_port: 4789
    jump: ACCEPT
